---
- name: Make sure {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: lscr.io/linuxserver/syncthing
    pull: yes
    privileged: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ data_dir }}:/data"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart_policy: unless-stopped