---
- hosts: all
  become: yes

  roles:
    # basics
    - role: system
      tags:
        - system
    - role: docker
      tags:
        - docker
    - role: mounts
      tags:
        - mounts

    # containers
    - role: containers/jellyfin
      become: no
      tags:
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/deluge
      become: no
      tags:
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: containers/radarr
      become: no
      tags:
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/sonarr
      become: no
      tags:
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/bazarr
      become: no
      tags:
        - bazarr
        - containers
      when: enable_bazarr | default(False)

    - role: containers/prowlarr
      become: no
      tags:
        - prowlarr
        - containers
      when: enable_prowlarr | default(False)

    - role: containers/openbooks
      become: no
      tags:
        - openbooks
        - containers
      when: enable_openbooks | default(False)

    - role: homer
      become: yes
      tags:
        - homer
      when: enable_homer | default(False)
