---
- hosts: all
  become: yes

  roles:
    # basics
    - role: system
      tags:
        - system
    - role: mounts
      tags:
        - mounts
    - role: docker
      tags:
        - docker

    # containers
    - role: containers/jellyfin
      become: no
      tags:
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/deluge
      become: no
      tags:
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: containers/radarr
      become: no
      tags:
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/sonarr
      become: no
      tags:
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/bazarr
      become: no
      tags:
        - bazarr
        - containers
      when: enable_bazarr | default(False)

    - role: containers/prowlarr
      become: no
      tags:
        - prowlarr
        - containers
      when: enable_prowlarr | default(False)

    - role: containers/portainer
      become: no
      tags:
        - portainer
        - containers
      when: enable_portainer | default(False)

    - role: containers/syncthing
      become: no
      tags:
        - syncthing
        - containers
      when: enable_syncthing | default(False)
    
    - role: containers/nginx
      become: no
      tags:
        - nginx
        - containers
      when: enable_nginx | default(False)

    - role: homer
      become: yes
      tags:
        - homer
        - containers
      when: enable_homer | default(False)
