---
- hosts: all
  become: yes

  roles:
    # basics
    - role: system
      tags:
        - system
    - role: docker
      tags:
        - docker
    - role: mounts
      tags:
        - mounts

    # security

    # containers
