---
- hosts: all
  become: yes

  roles:
    # basics
    - role: system
      tags:
        - system
    - role: docker
      tags:
        - docker
    - role: mounts
      tags:
        - mounts

    # security

    # containers
    - role: containers/jellyfin
      become: no
      tags:
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/arch-delugevpn
      become: no
      tags:
        - arch-delugevpn
        - containers
      when: enable_delugevpn | default(False)
