---
- name: Make sure the swag_public container is created and running
  docker_container:
    name: "swag_public"
    image: "ghcr.io/linuxserver/swag"
    pull: yes
    capabilities:
      - net_admin
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "URL": "{{ domain }}"
      "SUBDOMAINS": "wildcard"
      "VALIDATION": "dns"
      "DNSPLUGIN": "cloudflare"
      "EMAIL": "{{ email }}"
    ports:
      - "443:443"
    volumes:
      - "{{ docker_dir }}/swag/config/public/nginx:/config/nginx"
      - "{{ docker_dir }}/swag/dns-conf:/config/dns-conf"
      - "{{ docker_dir }}/swag/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped
