---
- name: Make sure that QuickSync packages are installed
  become: yes
  package:
    name:
      - vainfo
      - intel-media-va-driver-non-free
    state: present

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/jellyfin"
    pull: yes
    privileged: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ data_dir }}/media:/data/media"
    ports:
      - 8096:8096
    restart_policy: unless-stopped
