---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "evanbuss/openbooks"
    pull: yes
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    ports:
      - "8181:80"
    restart_policy: unless-stopped
