---
- name: Make sure the {{ container_name }} is created and running.
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jackett"
    pull: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
    ports:
      - 9117:9117
    restart_policy: unless-stopped
