---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "homer"
    image: "b4bz/homer"
    pull: true
    state: "started"
    ports:
      - 8080:8080
    env:
      "UID": "{{ guid }}"
      "GID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/www/assets"
    restart_policy: unless-stopped
