---
- name: Make sure {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "binhex/arch-delugevpn"
    pull: yes
    privileged: yes
    state: "started"
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - net_admin
    env:
      "VPN_ENABLED": "yes"
      "VPN_PROV": "custom"
      "VPN_CLIENT": "wireguard"
      "ENABLE_PRIVOXY": "yes"
      "LAN_NETWORK": "192.168.0.0/24"
      "NAME_SERVERS": "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1"
      "DELUGE_DAEMON_LOG_LEVEL": "info"
      "DELUGE_WEB_LOG_LEVEL": "info"
      "DEBUG": "false"
      "UMASK": "000"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ data_dir }}/torrents:/data/torrents"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    restart_policy: unless-stopped
