---
- name: Make sure {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "portainer/portainer-ce:latest"
    pull: yes
    privileged: yes
    state: "started"
    # networks:
    #   - default
    command: "-H unix:///var/run/docker.sock"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
    ports:
      - "9000:9000"
    restart_policy: unless-stopped