---
- name: Make sure {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "dyonr/qbittorrentvpn"
    pull: yes
    privileged: yes
    state: "started"
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    env:
      "VPN_ENABLED": "yes"
      "VPN_TYPE": "wireguard"
      "LAN_NETWORK": "0.0.0.0/24"
      "NAME_SERVERS": "1.1.1.1,1.0.0.1"
      "UMASK": "000"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
    volumes:
      - "/home/brandon/docker/qbittorrentvpn/config:/config"
      - "/mnt/passport:/downloads"
