---
- name: Install Prerequisites
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes

- name: Add Docker GPG apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ username }}" to group docker
  user:
    name: '{{ username }}'
    groups:
      - docker
    append: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Get a list of containers
  delegate_to: localhost
  become: no
  find:
    paths:
      - "roles/containers"
    file_type: directory
    recurse: no
  register: containers

- name: Stop and remove all disabled containers
  become: no
  docker_container:
    name: "{{ item.path.split('/')[-1] }}"
    state: absent
  when: not lookup('vars', 'enable_' + item.path.split('/')[-1])
  with_items: "{{ containers.files }}"
