---
- name: Include Ubuntu variables
  include_vars: "Ubuntu.yml"

- name: Install Prerequisites
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes

- name: Add Docker GPG apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes

- name: Add userpermissions
  shell: "usermod -aG docker {{ lookup('env','USER') }}"
