---
- name: Make sure the {{ container_name }} container is created and running.
  docker_container:
    name: "{{ container_name }}"
    image: "linuxserver/radarr"
    pull: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "002"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
      "DOCKER_MODS": "{{ theme_park_repo }}:{{ container_name }}"
      "TP_THEME": '{{ colorscheme | default("") }}'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ data_dir }}:/data"
    ports:
      - 7878:7878
    restart_policy: unless-stopped
