---
- name: Make sure the {{ container_name }} container is created and running.
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/radarr"
    pull: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "002"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ media_dir }}/Movies:/data/movies"
      - "{{ media_dir }}/Downloads:/data/downloads"
    ports:
      - 7878:7878
    restart_policy: unless-stopped
